cedaprode/encuesta/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic import ListView, DetailView
from django.views.generic.simple import direct_to_template
from models import Organizacion

urlpatterns = patterns('cedaprode.encuesta.views',
            url(r'^mis-encuestas/$', 'mis_encuestas', name='mis-encuestas'),
            url(r'^llenar-encuesta/(?P<encuesta_id>\d+)/$', 'llenar_encuesta', name='llenar-encuesta'),
            url(r'^adjuntar/(?P<encuesta_id>\d+)/$', 'adjuntar', name='adjuntar'),
            url(r'^extrainfo/(?P<encuesta_id>\d+)/$', 'informacion_extra', name='informacionextra'),
            url(r'^crear-encuesta/$', 'crear_encuesta', name='crear-encuesta'),
            url(r'^crear-organizacion/$', 'crear_organizacion', name='crear-organizacion'),
            url(r'^editar-organizacion/(?P<organizacion_id>\d+)/$', 'editar_organizacion', name='editar-organizacion'),
            url(r'^organizaciones/$', 'organizaciones', name='organizaciones'),
            url(r'^organizacion/(?P<pk>\d+)/$', 
                DetailView.as_view(model=Organizacion, template_name='encuesta/organizacion.html'), 
                name='organizacion-detalle'),
            url(r'^resultado/(?P<encuesta_id>\d+)/adjuntos/$', 'ver_adjuntos', name='ver-adjuntos'),
            url(r'^resultado/(?P<encuesta_id>\d+)/imprimir/$', 'resultado', 
                {'template_name': 'imprimir.html'}, name='imprimir'),
            url(r'^resultado/(?P<encuesta_id>\d+)/eliminar/$', 'eliminar_encuesta', name='eliminar'),
            url(r'^resultado/(?P<encuesta_id>\d+)/$', 'resultado',
                {'template_name': 'resultado.html'}, name='resultado'),
            url(r'^buscar-orgs/$', 'buscar_orgs', name='buscar-orgs'),
            url(r'^resultados/$', 'resultados', name='resultados'),
            url(r'^inicio/$', 'inicio', name='inicio'),
            url(r'^ayuda/$', direct_to_template, {'template': 'encuesta/ayuda.html'}, name='ayuda'),
            url(r'^$', 'index'),
            )

cedaprode/urls.py
from django.conf.urls.defaults import patterns, include, url
#from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()
import settings
from os import path as os_path

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='user-login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'registration/logout.html'}, name='user-logout'),
    url(r'^', include('cedaprode.encuesta.urls')),
    #url(r'^ejemplo', direct_to_template, {'template': 'encuesta/prueba.html'}),
)

if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^files/(.*)$', 'django.views.static.serve',
                             {'document_root': os_path.join(settings.MEDIA_ROOT)}),
                           )

cedaprode/encuesta/models.py
# -*- coding: UTF-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum

from cedaprode.lugar.models import Municipio

TIPOS_ORG = (
             ('1', 'Alcaldía'), 
             ('2', 'Sociedad civil'),
             ('3', 'Gremios'), 
             ('4', 'Instituciones del estado'), 
             ('5', 'Empresa'),
             ('6', 'Cooperativa')
            )

class Organizacion(models.Model):
    nombre = models.CharField(max_length=100)
    tipo = models.CharField(max_length=2, choices = TIPOS_ORG)
    descripcion = models.TextField() 
    creado_por = models.ForeignKey(User)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    municipio = models.ForeignKey(Municipio)
    representante = models.CharField('Representante legal', max_length=100)
    celular_repre = models.CharField('Celular', max_length=100, null=True, blank=True)
    correo_repre = models.CharField('Correo', max_length=100, null=True, blank=True)
    gerente = models.CharField(max_length=100, null=True, blank=True)
    celular_gerente = models.CharField('Celular', max_length=100, null=True, blank=True)
    correo_gerente = models.CharField('Correo', max_length=100, null=True, blank=True)
    fecha_fundacion = models.DateField()

    class Meta:
        verbose_name_plural = 'Organizaciones'
        verbose_name = 'Organización'

    def __unicode__(self):
        return self.nombre

   
class Encuesta(models.Model):
    organizacion = models.ForeignKey(Organizacion)
    fecha = models.DateField()
    usuario = models.ForeignKey(User)

    def save(self, *args, **kwargs):
        super(Encuesta, self).save(*args, **kwargs)
        #se registra cada pregunta en la encuesta
        for pregunta in Pregunta.objects.all():
            respuesta = Respuesta(pregunta = pregunta, encuesta = self)
            try:
                respuesta.save()
            except:
                pass

    def __unicode__(self):
        return 'Encuesta a %s con fecha %s' % (self.organizacion.nombre, self.fecha)
    
    def puntaje(self):
        puntos = Respuesta.objects.filter(encuesta = self).aggregate(p=Sum('respuesta__puntaje'))['p']
        if puntos:
            return puntos 
        else:
            return 0

class Adjunto(models.Model):
    encuesta = models.ForeignKey(Encuesta)
    archivo = models.FileField(upload_to="adjuntos")

    def __unicode__(self):
        return "Adjunto para %s" % self.encuesta
 
class Categoria(models.Model):
    '''Categoria principal'''
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()

    class Meta:
        verbose_name_plural = 'Categorías'

    def __unicode__(self):
        return self.titulo

class Pregunta(models.Model):
    categoria = models.ForeignKey(Categoria)
    titulo = models.TextField()

    def __unicode__(self):
        return self.titulo

class Opcion(models.Model):
    pregunta = models.ForeignKey(Pregunta)
    titulo = models.TextField()
    puntaje = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural = 'Opciones'
        unique_together = ['pregunta', 'puntaje']

    def __unicode__(self):
        return '%s= %s' % (self.puntaje, self.titulo)

class Respuesta(models.Model):
    encuesta = models.ForeignKey(Encuesta)
    pregunta = models.ForeignKey(Pregunta)
    respuesta = models.ForeignKey(Opcion, blank = True, null=True)
    comentario = models.TextField(blank=True, default='')

    class Meta:
        unique_together = ['encuesta', 'pregunta']
        ordering = ['pregunta__categoria', 'pregunta__id']

    def __unicode__(self):
        if self.respuesta:
            return '%s - %s(%s)' % (self.pregunta.titulo, 
                    self.respuesta.titulo, 
                    self.encuesta.usuario.username)
        else:
            return '%s - Sin responder(%s)' % (self.pregunta.titulo, 
                    self.encuesta.usuario.username)

#modelo nuevo para acicafoc
CHOICE_INTEGRADAS = (
                        (1, "Asamblea"),
                        (2, "Junta directiva"),
                        (3, "Junta de vigilancia"),
                        (4, "Comisión de formación"),
                        (5, "Comisión de género"),
                        (6, "Gerencia"),
                        (7, "Empleados")
                    )

CHOICE_FRECUENCIA = (
                        (1, "Semanal"),
                        (2, "Mensual"),
                        (3, "Bimensual"),
                        (4, "Trimestral"),
                        (5, "Semestral"),
                        (6, "Anual"),
                        (7, "No sesionan - no tiene información")
                    )

CHOICE_INTEGRADAS_FRECUENCIA = (
                        (1, "Sesiones de asamblea"),
                        (2, "Sesiones de junta directiva"),
                        (3, "Sesiones de junta de vigilancia"),
                        (4, "Sesiones de comisión de formación"),
                        (5, "Sesiones de comisión de género")
                    )

class ExtraInformacion(models.Model):
    encuesta = models.ForeignKey(Encuesta)
    integradas = models.IntegerField(choices=CHOICE_INTEGRADAS, null=True, blank=True)
    hombres = models.IntegerField(default=0 ,null=True, blank=True)
    mujeres = models.IntegerField(default=0, null=True, blank=True)

    def __unicode__(self):
        return u'%s hombre - %s mujeres' % (str(self.hombres),str(self.mujeres))

    class Meta:
        verbose_name_plural = "Extra información"

class RubrosManejados(models.Model):
    encuesta = models.ForeignKey(Encuesta)
    rubros = models.TextField('Rubros Manejados', null=True, blank=True)
    volumen_global = models.FloatField(default=0 ,null=True, blank=True)
    volumen_cacao = models.FloatField(default=0 ,null=True, blank=True)

    def __unicode__(self):
        return u'%s - %s' % (str(self.volumen_global),str(self.volumen_cacao))

    class Meta:
        verbose_name_plural = "Rubros manejados"

class FrecuenciaInfo(models.Model):
    encuesta = models.ForeignKey(Encuesta)
    tipos = models.IntegerField(choices=CHOICE_INTEGRADAS_FRECUENCIA)
    respuesta = models.IntegerField(choices=CHOICE_FRECUENCIA)

    def __unicode__(self):
        return u'%s tipos - %s respuesta' % (self.get_tipos_display(), self.get_respuesta_display())

    class Meta:
        verbose_name_plural = "Frecuencia Info"

cedaprode/encuesta/forms.py
from django import forms
from django.contrib.auth.models import User
from models import * 
from django.forms.extras.widgets import SelectDateWidget
import datetime

class RespuestaInlineForm(forms.ModelForm):
    pregunta = forms.ModelChoiceField(queryset = Pregunta.objects.all(), 
                                      widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        super(RespuestaInlineForm, self).__init__(*args, **kwargs)
        self.fields['respuesta'] = forms.ModelChoiceField(queryset = Opcion.objects.filter(pregunta=self.instance.pregunta), 
                                      widget=forms.RadioSelect(), empty_label=None, required=False)
    
    class Meta:
        model = Respuesta

class EncuestaForm(forms.ModelForm):
    usuario = forms.ModelChoiceField(queryset = User.objects.all(),
                                     widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        super(EncuestaForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['organizacion'] = forms.ModelChoiceField(queryset = Organizacion.objects.filter(creado_por=self.instance.usuario))
    
    class Meta:
        model = Encuesta

#YEAR_CHOICES = ('2009','2010','2011', '2012', '2013','2014', '2015', '2016','2017', '2018', '2019')
#hoy = datetime.date.today()

class OrganizacionForm(forms.ModelForm):
    creado_por = forms.ModelChoiceField(queryset = User.objects.all(),
                                     widget=forms.HiddenInput)
    #fecha_fundacion = forms.DateField(label="Fecha fundacion",widget=SelectDateWidget(years=YEAR_CHOICES), initial=hoy)

    class Meta:
        model = Organizacion
        widgets = {    
            'municipio' : forms.Select(attrs={'class':'chosen'})
            }

class BuscarForm(forms.Form):
    municipio = forms.ModelChoiceField(queryset = Municipio.objects.all(), required=False)
    tipo = forms.ChoiceField(choices = TIPOS_ORG, required=False)

class BuscarResultadoForm(forms.Form):
    tipo = forms.ChoiceField(choices = TIPOS_ORG, required=False)
    municipio = forms.ModelChoiceField(queryset = Municipio.objects.all(), required=False)

class AdjuntoForm(forms.ModelForm):
    encuesta = forms.ModelChoiceField(queryset = Encuesta.objects.all(), widget=forms.HiddenInput)

    class Meta:
        model = Adjunto

#formulario extra para acicafoc

class ExtraInformacionForm(forms.ModelForm):

    # def __init__(self, *args, **kwargs):
    #     super(ExtraInformacionForm, self).__init__(*args, **kwargs)
    #     for datos in CHOICE_INTEGRADAS:
    #         self.fields['integradas'].initial = datos
        #self.fields['hombres'] = forms.IntegerField(required=False)
        #self.fields['mujeres'] = forms.IntegerField(required=False)

    class Meta:
        model = ExtraInformacion
        exclude = ('encuesta',)

class RubrosManejadosForm(forms.ModelForm):
    
    class Meta:
        model = RubrosManejados
        fields = ('rubros', 'volumen_global', 'volumen_cacao')

class FrecuenciaInfoForm(forms.ModelForm):
    
    class Meta:
        model = FrecuenciaInfo
        exclude = ('encuesta',)

cedaprode/templates/encuesta/adjuntar.html
{%extends "base2.html"%}
{%load clasificador %}
{%block title%}Adjuntar{%endblock%}
{%block extra_head%}
{%endblock%}
{%block content%}
<div  style="padding:15px;">
    <h2 class="left">Adjuntar Documento a Encuesta</h2>
    <br>
    <form action="." method="POST" accept-charset="utf-8" enctype="multipart/form-data" id="encuesta">
      {% csrf_token %}
      {{form.as_p}}
    <input type="submit" value="Adjuntar">
    </form>
    <div class="separador"></div>
</div>
{%endblock%}

cedaprode/templates/encuesta/buscar_orgs.html
{% extends "base2.html" %}
{%block title%}Organizaciones{%endblock%}
{% block content %}
<div style="padding:15px;">
    <h1><a href="{% url crear-organizacion%}"><img class="der" src="/files/imagen/nuev.jpg"></a></h1>

    <h2 class="left">MIS ORGANIZACIONES</h2>
    <div class="separador"><br></div>
    <div class="tabla">
    <table>
        <tr>
           <th>Nombre</th>
           <th>Tipo</th>
           <th>Municipio</th>
           <th>Accion</th>
        </tr>
        {% for organizacion in organizaciones%}
        <tr>
           <td><b>{{ organizacion.nombre }}</b> </td>
           <td>{{ organizacion.get_tipo_display }} </td>
           <td>{{ organizacion.municipio.nombre }} </td>
           <td><a href="{% url organizacion-detalle organizacion.id %}">Ver</a> | <a href="{% url editar-organizacion organizacion.id %}">Editar</a></td>
        </tr>
        {% endfor %}
    </table>
    </div>
    <form action="{%url buscar-orgs %}" method="POST" accept-charset="utf-8">
      {% csrf_token %}
      {{form.as_p}}
    <p><input type="submit" value="Continue &rarr;"0></p>
      {{form.errors}}
    </form>
</div>

{% endblock %}
{%block sidebar%}
<div id="user-info" style="padding:15px;">
      <img src="/files/imagen/user.png" align="left"></img>
      <div id="usuario">{{request.user.get_full_name}}</div>
      <div id="mail">{{request.user.email}}</div>
      <div class="separador"></div>
      <div id="misorg">MIS ORGANIZACIONES</div>
      </br>
      {% for organizacion in object_list %}
        <a href="#">{{organizacion.nombre}}</a>
      {% endfor %}
      <div class="separador"></div>
</div>
{%endblock%}

cedaprode/templates/encuesta/crear_encuesta.html
{%extends "base2.html"%}
{%block title%}Formulario{%endblock%}
{% block extra_head %}
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
 <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
 <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
<script>
  $(function() {
    $( "#id_fecha" ).datepicker({ dateFormat: 'dd/mm/yy', dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'], monthNamesShort: ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],changeMonth: true, changeYear: true});
  });
  </script>

{% endblock extra_head %}
{%block content%}
<div  style="padding:15px;">
<form action="." method="POST" accept-charset="utf-8">

  {% csrf_token %}
  {{form.as_p}}
<div id="agregar" class="boton_guardar">
<p><input type="submit" value="Continue &rarr;"></p>
</div>
</form>
</div>
{%endblock%}

cedaprode/templates/encuesta/crear_organizacion.html
{%extends "base2.html"%}
{%block title%}Formulario{%endblock%}
{%block extra_head%}
<link rel="stylesheet" href="/files/css/chosen.css">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
 <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
 <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
<script src="/files/js/chosen.jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
  jQuery(document).ready(function(){
  jQuery(".chosen").chosen();
}); 
</script>

<script>
  $(function() {
    $( "#id_fecha_fundacion" ).datepicker({ dateFormat: 'dd/mm/yy', dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'], monthNamesShort: ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],changeMonth: true, changeYear: true});
  });
  </script>

{%endblock%}
{%block content%}
<div  style="padding:15px;">
    <div class="text_hform">Agregar Organizaciones</div>
<form action="." method="POST" accept-charset="utf-8">
  {% csrf_token %}
  {{form.errors}}
  {{ form.creado_por }}

  <div class="boxdiv">
      <span class="textform">{{ form.nombre.label_tag }}</span><br/><br/>
      {{ form.nombre }}
  </div>

  <div class="boxdiv">
      <span class="textform">{{ form.tipo.label_tag }}</span><br/><br/>
      {{ form.tipo }}
  </div>

  <div class="boxdiv">
      <span class="textform">{{ form.descripcion.label_tag }}</span><br/><br/>
      {{ form.descripcion }}
  </div>

<div class="boxdiv_1">
      <span class="textform">{{ form.municipio.label_tag }}</span><br/><br/>
      <div class="form-auto">{{ form.municipio }}</div>
  </div>


<div class="boxdiv">
      <span class="textform">{{ form.representante.label_tag }}</span><br/><br/>
      {{ form.representante }}
  </div>

<div class="boxdiv">
      <span class="textform">{{ form.celular_repre.label_tag }}</span><br/><br/>
      {{ form.celular_repre }}
  </div>

<div class="boxdiv">
      <span class="textform">{{ form.correo_repre.label_tag }}</span><br/><br/>
      {{ form.correo_repre }}
  </div>

<div class="boxdiv">
      <span class="textform">{{ form.gerente.label_tag }}</span><br/><br/>
      {{ form.gerente }}
  </div>

  <div class="boxdiv">
      <span class="textform">{{ form.celular_gerente.label_tag }}</span><br/><br/>
      {{ form.celular_gerente }}
  </div>

  <div class="boxdiv">
      <span class="textform">{{ form.correo_gerente.label_tag }}</span><br/><br/>
     {{ form.correo_gerente }}
  </div>

  <div class="boxdiv">
      <span class="textform">{{ form.fecha_fundacion.label_tag }}</span><br/><br/>
     {{ form.fecha_fundacion }}
  </div>

<div id="agregar" class="boton_guardar">
<p><input type="submit" value="Guardar" ></p>
</div>

</form>
</div>
{%endblock%}

cedaprode/templates/encuesta/resultado.html
{%extends "base2.html"%}
{%load truncador%}
{%block title%}Resultado{%endblock%}
{%block extra_head%}
    <link href="/files/css/jquery-ui-1.8.12.custom.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="/files/css/vtip.css" rel="stylesheet" type="text/css" media="screen" />
    <script type="text/javascript" src="/files/js/jquery-ui-1.8.12.custom.min.js"></script>
    <script type="text/javascript" src="/files/js/vtip-min.js"></script>
    <script type="text/javascript" src="/files/js/highcharts.js"></script>
    <script type="text/javascript" src="/files/js/exporting_patched.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){

                // Tabs
                $('#tabs').tabs();
                $('#grafos').tabs();

                //hover states on the static widgets
                $('#dialog_link, ul#icons li').hover(
                    function() { $(this).addClass('ui-state-hover'); },
                    function() { $(this).removeClass('ui-state-hover'); }
                );
            });
            var chart;
$(document).ready(function() {
   chart = new Highcharts.Chart({
      chart: {
         renderTo: 'highchart',
         defaultSeriesType: 'bar',
         width: 650,
         height: 450,
      },
      title: {
         text: 'Consolidado'
      },
      xAxis: {
         //preguntas
         categories: [{%for legend in url_grafo.barra.legends%} '{{legend}}',{%endfor%}]
         //categories: ['la puta madre','acción 10']
      },
      yAxis: {
         min: 0,
         title: {
            text: 'Puntaje total'
         }
      },
      legend: {
         //backgroundColor: Highcharts.theme.legendBackgroundColorSolid || '#FFFFFF',
         reversed: true
      },
      tooltip: {
        enabled: false
      },
      plotOptions: {
         series: {
            stacking: 'normal',
            dataLabels: {
                enabled: true,
                align: 'center',
                color: '#000',
                formatter: function() {
                  if (this.series.name == 'Puntaje total'){
                    return '' + this.point.stackTotal;
                  }else {
                    return ''+ this.y;
                  }
                 },
                style: {
                    font: '12px Trebuchet MS, Verdana, sans-serif'
                }
            }

         }
      },
         series: [{ //puntajes
         name: 'Puntaje total',
         data: {{url_grafo.barra.data.1}}
      }, {
         name: 'Puntaje Obtenido',
         data: {{url_grafo.barra.data.0}}
      }]
   });


});
        </script>
{%endblock%}
{% block content %}
<div  style="padding:15px;">
  <h2 class="left"> RESULTADO DE LA EVALUACION</h2>
  <a href="{% url imprimir encuesta.id %}"><div class="boton_print">Imprimir</div></a>
  <div class="separador"></div>
  <div class="tabla">
      <table class="table table-hover">
        <tr>
          <td><b>ORGANIZACION</b></td>
          <td>{{encuesta.organizacion}}</td>
        </tr>
        <tr>
          <td><b>TIPO</b></td>
          <td>{{encuesta.organizacion.get_tipo_display}}</td>
        </tr>
        <tr>
          <td><b>DESCRIPCION</b></td>
          <td>{{encuesta.organizacion.descripcion}}</td>
        </tr>
        <tr>
          <td><b>REPRESENTANTE LEGAL</b></td>
          <td>{{encuesta.organizacion.representante}} - {{encuesta.organizacion.correo_repre}} - {{encuesta.organizacion.celular_repre}}</td>
        </tr>
        <tr>
          <td><b>GERENTE</b></td>
          <td>{{encuesta.organizacion.gerente}} - {{encuesta.organizacion.correo_gerente}} - {{encuesta.organizacion.celular_gerente}}</td>
        </tr>
        <tr>
          <td><b>FECHA DE FUNDACION</b></td>
          <td>{{encuesta.organizacion.fecha_fundacion}}</td>
        </tr>
        <tr>
          <td><b>FECHA DE EVALUACION</b></td>
          <td>{{encuesta.fecha}}</td>
        </tr>
        <tr>
          <td><b>AUTOR</b></td>
          <td>{{encuesta.usuario.get_full_name}}</td>
        </tr>
        {%if adjuntos %}
        <tr>
          <td><b>DOCUMENTOS ADJUNTOS</b></td>
          <td>{%for adjunto in adjuntos%}<a href="/files/{{adjunto.archivo}}">{{adjunto.archivo.name}}</a><br>{%endfor%}</td>
        </tr>
        {%endif%}
        {%if encuesta.extrainformacion_set.all %}
        <tr>
          <td><b>PERSONAS INTEGRADAS EN</b></td>
          <td>{%for objetos in encuesta.extrainformacion_set.all%}
            {{objetos.get_integradas_display}}:
                Hombres: {{objetos.hombres}}
                Mujeres: {{objetos.mujeres}}<br>
            {%endfor%}</td>
        </tr>
        {%endif%}
        {%if encuesta.rubrosmanejados_set.all %}
        <tr>
          <td><b>RUBROS MANEJADOS</b></td>
          <td>{%for objetos in encuesta.rubrosmanejados_set.all%}
                {{objetos.rubros}}<br>
                Volumen global: {{objetos.volumen_global}}<br>
                Volumen cacao: {{objetos.volumen_cacao}}<br>
              {%endfor%}</td>
        </tr>
        {%endif%}
        {%if encuesta.frecuenciainfo_set.all %}
        <tr>
          <td><b>FRECUENCIA DE </b></td>
          <td>{%for objetos in encuesta.frecuenciainfo_set.all%}
                {{objetos.get_tipos_display}}:{{objetos.get_respuesta_display}}<br>
              {%endfor%}</td>
        </tr>
        {%endif%}
      </table>

  </div>
    <div id="tabs">
      <ul>
        <li><a class="algo" href="#tabs-consolidado">Consolidado</a></li>
      {%for fila in resultados%}
        <li><a class="algo" href="#tabs-{{fila.categoria.id}}">{{fila.categoria.titulo|truncador:"2"}}</a></li>
      {%endfor%}
    </ul>
    {%for fila in resultados%}
        <div id="tabs-{{fila.categoria.id}}">
            <b style="font-size:16px;">{{fila.categoria}}</b><br><br>
            <div class="tabla" >
            <table>
              <tr><th>Pregunta</th><th>Puntaje Obtenido</th><th>Comentario</th></tr>
              {% for resp in fila.respuestas%}
              <tr>
                <td>{{resp.pregunta}}</td>
                <td>{{resp.respuesta.puntaje|default:"0"}}/5</td>
                <td><a href="" title="{{resp.comentario}}" class="vtip">{{resp.comentario|truncatewords:"10"}}</a></td>
              </tr>
              {%endfor%}
              <tr><td>TOTAL</td><td>{{fila.puntaje|default_if_none:"0"}}/{{fila.total_maximo}}</td></tr>
            </table>
            </div>
            <div id="grafo-{{fila.categoria.id}}" style="width:100%; background:#fff;"><br><center><img src="{{fila.grafo_url}}" /></center></div>
        </div>
    {%endfor%}
        <div id="tabs-consolidado">
            <b style="font-size:16px;">Consolidado</b><br><br>
            <div class="tabla" >
            <table>
              <tr><th>Pregunta</th><th>Puntaje Obtenido</th></tr>
              {% for fila in resultados%}
              <tr>
                <td>{{fila.categoria}}</td>
                <td>{{fila.puntaje|default:"0"}}/{{fila.total_maximo}}</td>
              </tr>
              {%endfor%}
              <tr><td>TOTAL</td><td>{{encuesta.puntaje}}/180</td></tr>
            </table>
            </div>
              <div id="grafos">
              <ul>
                <li><a class="algo" href="#grafo-consolidado-radar">Consolidado Radar</a></li>
                <li><a class="algo" href="#grafo-consolidado-barra">Consolidado Barra</a></li>
              </ul>
                  <div id="grafo-consolidado-radar" style="width:100%; background:#fff;"><br><center><img src="{{url_grafo.radar}}" /></center>*Este gráfico está normalizado</div>
                  <div id="grafo-consolidado-barra" style="width:100%; background:#fff;"><br><center>
                  <div id="highchart"></div>
                  </center></div>
        </div>
    </div>
</div>
{% endblock %}